# This is a basic workflow to help you get started with Actions
name: tag based workflow
# Controls when the workflow will run
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*' 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out from Git
      uses: actions/checkout@v3
    - name: Check if Git tag exists
      run: ls -ltra
    - name: tag job
      run : echo This is what a tag based action look like
