# This is a basic workflow to help you get started with Actions
name: when PR is merged into dev
# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'tag version (release version)'
        required: true
        default: 'v1.0.0'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out from Git
      uses: actions/checkout@v3
    - name: Check if Git tag exists
      run: echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"
